location/Models/voiture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace location.Models
{
    public class voiture
    {
        public enum TypeCarburant
        {
            ParDefaut,
            Essance,
            Diesel
        }
        [Key]
        public int voitureID { get; set; }
        public String numero_matriculation { get; set; }
        [Required]
        [Column(TypeName = "date"), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime date_mise_circulation { get; set; }
        [Required]
        [Range(100, 600)]
        public int prix_Par_Jour { get; set; }
        [Required]
        public TypeCarburant? carburant { get; set; }
        public String image { get; set; }
        public int categorieID { get; set; }

        public virtual categorie Categorie { get; set; }
        public int modelID { get; set; }
        public virtual Modele Modele { get; set; }
        [NotMapped]
        public HttpPostedFileBase Imagevoiture { get; set; }

    }
}

location/Controllers/voituresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using location.Models;

namespace location.Controllers
{
    public class voituresController : Controller
    {
        private GCDB db = new GCDB();

        // GET: voitures
        public ActionResult Index()
        {
            var voitures = db.voitures.Include(v => v.Categorie).Include(v => v.Modele);
            return View(voitures.ToList());
        }

        // GET: voitures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            return View(voiture);
        }

        // GET: voitures/Create
        public ActionResult Create()
        {
            ViewBag.categorieID = new SelectList(db.categories, "CategorieID", "CategorieID");
            ViewBag.modelID = new SelectList(db.Modeles, "modelID", "nom");
            return View();
        }

        // POST: voitures/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(voiture voiture)
        {
            string filename = Path.GetFileNameWithoutExtension(voiture.Imagevoiture.FileName);
            string extention = Path.GetExtension(voiture.Imagevoiture.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extention;
            voiture.image = "../Image/" + filename;
            filename = Path.Combine(Server.MapPath("../Image/"), filename);
            voiture.Imagevoiture.SaveAs(filename);
            if (ModelState.IsValid)
            {
                db.voitures.Add(voiture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categorieID = new SelectList(db.categories, "CategorieID", "CategorieID", voiture.categorieID);
            ViewBag.modelID = new SelectList(db.Modeles, "modelID", "nom", voiture.modelID);
            return View(voiture);
        }

        // GET: voitures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            ViewBag.categorieID = new SelectList(db.categories, "CategorieID", "CategorieID", voiture.categorieID);
            ViewBag.modelID = new SelectList(db.Modeles, "modelID", "nom", voiture.modelID);
            return View(voiture);
        }

        // POST: voitures/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "voitureID,numero_matriculation,date_mise_circulation,prix_Par_Jour,carburant,image,categorieID,modelID")] voiture voiture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(voiture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categorieID = new SelectList(db.categories, "CategorieID", "CategorieID", voiture.categorieID);
            ViewBag.modelID = new SelectList(db.Modeles, "modelID", "nom", voiture.modelID);
            return View(voiture);
        }

        // GET: voitures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            voiture voiture = db.voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            return View(voiture);
        }

        // POST: voitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            voiture voiture = db.voitures.Find(id);
            db.voitures.Remove(voiture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

location/Views/voitures/Create.cshtml
@model location.Models.voiture

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container pt-3">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            @using (Html.BeginForm("Create", "voitures", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>voiture</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.numero_matriculation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.numero_matriculation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.numero_matriculation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.date_mise_circulation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.date_mise_circulation, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.date_mise_circulation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.prix_Par_Jour, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.prix_Par_Jour, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.prix_Par_Jour, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.carburant, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.carburant, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.carburant, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })*@
                        <input type="file" name="Imagevoiture" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.categorieID, "categorieID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("categorieID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.categorieID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.modelID, "modelID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("modelID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.modelID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">

                    <input type="submit" value="Create" class="btn btn-primary" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-outline-secondary" })

                </div>
            </div>
            }
        </div>
    </div>
</div>




<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

location/Views/voitures/Delete.cshtml
@model location.Models.voiture

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>voiture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categorie.CategorieID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.CategorieID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modele.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modele.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numero_matriculation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero_matriculation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_mise_circulation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_mise_circulation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prix_Par_Jour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix_Par_Jour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.carburant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.carburant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

location/Views/voitures/Details.cshtml
@model location.Models.voiture

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>voiture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categorie.CategorieID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.CategorieID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modele.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modele.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numero_matriculation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero_matriculation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_mise_circulation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_mise_circulation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prix_Par_Jour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix_Par_Jour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.carburant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.carburant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.voitureID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

location/Views/voitures/Edit.cshtml
@model location.Models.voiture

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>voiture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.voitureID)

        <div class="form-group">
            @Html.LabelFor(model => model.numero_matriculation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero_matriculation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero_matriculation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_mise_circulation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_mise_circulation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_mise_circulation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prix_Par_Jour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix_Par_Jour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix_Par_Jour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.carburant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.carburant, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.carburant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categorieID, "categorieID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("categorieID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categorieID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelID, "modelID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("modelID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.modelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

location/Views/voitures/Index.cshtml
@model IEnumerable<location.Models.voiture>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Modele.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modele.serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.numero_matriculation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categorie.type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date_mise_circulation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prix_Par_Jour)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.carburant)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>

    <td>
        @Html.DisplayFor(modelItem => item.Modele.nom)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Modele.serie)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.numero_matriculation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Categorie.type)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.date_mise_circulation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.prix_Par_Jour)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.carburant)
    </td>
    <td>
        @*@Html.DisplayFor(modelItem => item.image)*@
        <img src="@item.image" width="150" height="150" />
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.voitureID }, new { @class = "btn btn-outline-success" }) 
        @Html.ActionLink("Details", "Details", new { id = item.voitureID }, new { @class = "btn btn-outline-primary" }) 
        @Html.ActionLink("Delete", "Delete", new { id = item.voitureID }, new { @class = "btn btn-outline-danger" })
    </td>
</tr>
}

</table>