location/Models/clt.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace location.Models
{
    
    public class clt
    {
        [Key] // ==> PRIMARY KEY
        public int CID { get; set; }
        [Required]
        // ==> NOT NULL
        [MinLength(4), MaxLength(100)]
        public string Nom { get; set; }
        [Required]
        [MaxLength(100)]
        [EmailAddress]
        public string AdresseMail { get; set; }
        [Required]
        [MaxLength(100)]
        [DataType(DataType.Password)]
        public string MotDePasse { get; set; }
        [Required]
        [Column(TypeName = "date"), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateNaissance { get; set; }

        public String CIN { get; set; }

        public String permis { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageCin { get; set; }
        [NotMapped]
        public HttpPostedFileBase Imagepermis { get; set; }
        public Boolean IsAdmin { get; set; }

        public clt()
        {
            IsAdmin = true;

        }
    }
}

location/Controllers/cltsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using location.Models;

namespace location.Controllers
{
    public class cltsController : Controller
    {
        private GCDB db = new GCDB();

        // GET: clts
        public ActionResult Index()
        {
            return View(db.clts.ToList());
        }

        // GET: clts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clt clt = db.clts.Find(id);
            if (clt == null)
            {
                return HttpNotFound();
            }
            return View(clt);
        }

        // GET: clts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: clts/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(clt clt)
        {//Imagepermis
            string filename = Path.GetFileNameWithoutExtension(clt.ImageCin.FileName);
            string extention = Path.GetExtension(clt.ImageCin.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extention;
            clt.CIN = "../Image/" + filename;
            filename = Path.Combine(Server.MapPath("../Image/"), filename);
            clt.ImageCin.SaveAs(filename);
            //********************************
            string filename1 = Path.GetFileNameWithoutExtension(clt.Imagepermis.FileName);
            string extention1 = Path.GetExtension(clt.Imagepermis.FileName);
            filename1 = filename1 + DateTime.Now.ToString("yymmssfff") + extention1;
            clt.permis = "../Image/" + filename1;
            filename1 = Path.Combine(Server.MapPath("../Image/"), filename1);
            clt.Imagepermis.SaveAs(filename1);

            if (ModelState.IsValid)
            {
                db.clts.Add(clt);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clt);
        }

        // GET: clts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clt clt = db.clts.Find(id);
            if (clt == null)
            {
                return HttpNotFound();
            }
            return View(clt);
        }

        // POST: clts/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CID,Nom,AdresseMail,MotDePasse,DateNaissance,CIN,permis")] clt clt)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clt);
        }

        // GET: clts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            clt clt = db.clts.Find(id);
            if (clt == null)
            {
                return HttpNotFound();
            }
            return View(clt);
        }

        // POST: clts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            clt clt = db.clts.Find(id);
            db.clts.Remove(clt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

location/Views/clts/Create.cshtml
@model location.Models.clt

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Create</h2>*@
<div class="container pt-3">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            @using (Html.BeginForm("Create", "clts", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>clt</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.AdresseMail, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AdresseMail, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AdresseMail, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MotDePasse, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MotDePasse, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                            @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DateNaissance, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateNaissance, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                            @Html.ValidationMessageFor(model => model.DateNaissance, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CIN, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.CIN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CIN, "", new { @class = "text-danger" })*@
                            <input type="file" name="ImageCin" />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.permis, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="Imagepermis" />
                        </div>
                    </div>

                    <div class="form-group">
                        
                            <input type="submit" value="Create" class="btn btn-primary" />
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-outline-secondary" })
                      
                    </div>
                </div>
            }
        </div>
    </div>
</div>



<div>
   
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

location/Views/clts/Delete.cshtml
@model location.Models.clt

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>clt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdresseMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdresseMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotDePasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotDePasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.permis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.permis)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

location/Views/clts/Details.cshtml
@model location.Models.clt

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>clt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdresseMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdresseMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotDePasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotDePasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CIN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.permis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.permis)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

location/Views/clts/Edit.cshtml
@model location.Models.clt

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>clt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdresseMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdresseMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdresseMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MotDePasse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MotDePasse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateNaissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateNaissance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateNaissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CIN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CIN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.permis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.permis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.permis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

location/Views/clts/Index.cshtml
@model IEnumerable<location.Models.clt>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover table-striped" >
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdresseMail)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.permis)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AdresseMail)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.DateNaissance)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.CIN)*@
            <img src="@item.CIN" width="120" height="120"/>
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.permis)*@
            <img src="@item.permis" width="120" height="120" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CID }, new { @class = "btn btn-outline-success" }) 
            @Html.ActionLink("Details", "Details", new { id=item.CID }, new { @class = "btn btn-outline-primary" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.CID }, new { @class = "btn btn-outline-danger" })
        </td>
    </tr>
}

</table>